pong-apex:
    env: PongNoFrameskip-v4
    run: APEX
    stop:
        timesteps_total: 2000000
    config:
        # Works for both torch and tf.
        optimizer:
            max_weight_sync_delay: 400
            num_replay_buffer_shards: 2
            debug: False
        framework: tf
        target_network_update_freq: 20000
        num_workers: 2
        num_envs_per_worker: 5
        lr: .00005
        train_batch_size: 64
        gamma: 0.99
        num_cpus_per_worker: 1
        buffer_size: 200000
        num_gpus: 0
        num_gpus_per_worker: 0
 
